package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

    Cart selectCartByUserIdAndProductId(@Param("userId")Integer userId,
                                        @Param("productId")Integer productId);
    List<Cart> selectCartByUserId(Integer userId);
    int isCheckedAll(Integer userId);

    //删除购物车某些商品
    int deleteByUseridAndProductIds(@Param("userId")Integer userId,
                                    @Param("productIdList")List<Integer> productIdList);
    /*
    操作购物车商品是否选中
     */
    int selectOrUnselectProduct(@Param("userId") Integer userId,
                                @Param("productId") Integer productId,
                                @Param("check") Integer check);
    //统计购物车中产品的总数量
    int get_cart_product_count(Integer userId);
    //查询用户已经选中的商品
    List<Cart>  findCartListByUserIdAndChecked(Integer userId);
    //批量删除购物车商品
    int batchDelete(List<Cart> cartList);

}